### ISSUE TITLE
Peer-to-peer morning session code Reviews

### ISSUE THREAD

**Issue by medsonmoombe** [Ghilain/Leaderboard#3]
## Hello @Ghilain  nice work so far your project looks good and the post and get methods works perfectly but we recommend you consider adding the following to make it works more perfect.
- It is good practice and mostly recommended to use error handling methods like Catch to address the error whenever your functions fails to get or post the data from the the Api due to some network issues or others.
- We also feel it will be perfect if in the first input for the name you only allow text to be entered , to avoid getting different data types like numeric values in field.

**Comment by Ghilain** [comment]
Thank you
